FROM twiliodeved/api-snippets:java

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV RUN_ENV=test
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV FAKE_CERT_PATH=/twilio-api-faker/keystore/twilio_fake.pem
ENV GRADLE_OPTS="-Dorg.gradle.daemon=true"

RUN mkdir /usr/local/rvm/src/rvm/rubies
RUN mkdir /usr/local/rvm/src/rvm/archives
RUN mkdir /usr/local/rvm/src/rvm/src

RUN ["/bin/bash", "-l", "-c", "echo 'source /usr/local/rvm/src/rvm/scripts/rvm' > ~/.bashrc"]
RUN ["/bin/bash", "-l", "-c", "source ~/.bashrc"]
RUN ["/bin/bash", "-l", "-c", "rvm requirements"]
RUN ["/bin/bash", "-l", "-c", "rvm install ruby-2.4"]
RUN ["/bin/bash", "-l", "-c", "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"]
RUN ["/bin/bash", "-l", "-c", "gem install bundler --no-ri --no-rdoc"]

RUN git clone https://github.com/TwilioDevEd/twilio-api-faker.git && \
    cp /twilio-api-faker/keystore/twilio_fake.pem /usr/local/share/ca-certificates/twilio_fake.crt

RUN update-ca-certificates

RUN gem install json colorize nokogiri

RUN pip install virtualenvwrapper

RUN mkdir /.virtualenvs

ENV WORKON_HOME /.virtualenvs

RUN /bin/bash -l -c "source /usr/local/bin/virtualenvwrapper.sh"
